DROP TABLE IF EXISTS LOGIN_CREDENTIALS;

CREATE TABLE LOGIN_CREDENTIALS (
    CREDENTIAL_KEY VARCHAR(50) PRIMARY KEY,
    USERNAME VARCHAR(100),
    PASSWORD VARCHAR(100)
);

INSERT INTO LOGIN_CREDENTIALS (CREDENTIAL_KEY, USERNAME, PASSWORD)
VALUES ('standard_user', 'standard_user', 'secret_sauce');

INSERT INTO LOGIN_CREDENTIALS (CREDENTIAL_KEY, USERNAME, PASSWORD)
VALUES ('locked_out_user', 'locked_out_user', 'secret_sauce');

INSERT INTO LOGIN_CREDENTIALS (CREDENTIAL_KEY, USERNAME, PASSWORD)
VALUES ('invalid_user', 'invalid_user', 'wrong_password');
